export const TITLE_FORMCREATEANCCOUNT="#create-account_form > .page-subheading"
export const INPUT_EMAIL="#email_create"
export const BUTTON_CREATEANACCOUNT="#SubmitCreate > span"
export const H1_AUTHENTICATION=".page-heading"
export const H1_LOGIN='#login_form > .page-subheading'
export const LOGIN_EMAIL='#email'
export const LOGIN_PASSWORD='#passwd'
export const LINK_FORGOT_PASSWORD='.lost_password > a'
export const LOGIN_BUTTON='#SubmitLogin > span'
export const ERROR_CREATEANACCOUNT='#create_account_error'
export const ERROR_LOGIN='ol > li'